apiVersion: v1
kind: Service
metadata:
  name: kafka-broker
  labels:
    app.kubernetes.io/app: kafka
    app.kubernetes.io/component: kafka-broker    
spec:
  clusterIP: None
  ports:
  - port: 9092
    name: kafka-port
    targetPort: 9092
    protocol: TCP
  selector:
    app.kubernetes.io/app: kafka
    app.kubernetes.io/component: kafka-broker