apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-zk
  labels:
    app.kubernetes.io/app: kafka
    app.kubernetes.io/component: kafka-zk
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/app: kafka-zk      
  template:
    metadata:
      labels:
        app.kubernetes.io/app: kafka-zk
        app.kubernetes.io/component: kafka-zk      
    spec:
      containers:
      - name: kafka-zk
        image: confluentinc/cp-zookeeper:5.5.2
        ports:
        - containerPort: 2181
        env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
