apiVersion: v1
kind: Service
metadata:
  name: kafka-zk
  labels:
    app.kubernetes.io/app: kafka
    app.kubernetes.io/component: kafka-zk    
spec:
  ports:
  - name: client
    port: 2181
    protocol: TCP
  - name: follower
    port: 2888
    protocol: TCP
  - name: leader
    port: 3888
    protocol: TCP
  selector:
    app.kubernetes.io/app: kafka-zk
    app.kubernetes.io/component: kafka-zk
