apiVersion: v1
kind: Service
metadata:
  name: minio-console-lb
  namespace: minio
  labels:
    app.kubernetes.io/component: loadbalancer
    app.kubernetes.io/name: minio
spec:
  ports:
  - port: 9001
    targetPort: 9001
    protocol: TCP    
  selector:
    app.kubernetes.io/component: backend
    app.kubernetes.io/name: minio
  type: LoadBalancer