apiVersion: v1
kind: Service
metadata:
  name: minio-console-svc
  namespace: minio
  labels:
    app.kubernetes.io/name: minio-console-svc
    app.kubernetes.io/component: service
spec:
  ports:
  - name: http
    protocol: TCP  
    port: 9001
    targetPort: 9001
  selector:
    app.kubernetes.io/name: minio
    app.kubernetes.io/component: backend