apiVersion: v1
kind: Pod
metadata:
  name: minio-mc
  namespace: minio
  labels:
    app.kubernetes.io/name: minio-mc
    app.kubernetes.io/component: cli  
spec:
  restartPolicy: Never 
  containers:
    - name: minio-mc
      image: minio/mc
      imagePullPolicy: IfNotPresent
      command: ["/app/mc-init.sh"]
      volumeMounts:
        - name: mc-config
          mountPath: "/app"      
      env:
        - name: MINIO_SERVER_HOST
          value: "http://minio-server-svc.minio"
        - name: MINIO_SERVER_PORT_NUMBER
          value: "9000"
        - name: MINIO_SERVER_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-admin-creds
              key: username
        - name: MINIO_SERVER_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: minio-admin-creds
              key: password
  volumes:
    - name: mc-config
      configMap:
        name: mc-config
        defaultMode: 0745              
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mc-config
  namespace: minio
  labels:
    app.kubernetes.io/name: minio-mc
    app.kubernetes.io/component: config
data:
  mc-init.sh: |
    #!/bin/sh
    mc alias set minio $MINIO_SERVER_HOST:$MINIO_SERVER_PORT_NUMBER $MINIO_SERVER_ACCESS_KEY $MINIO_SERVER_SECRET_KEY
    while true; do sleep 5s; done