apiVersion: v1
kind: Service
metadata:
  name: minio-server-svc
  namespace: minio
  labels:
    app.kubernetes.io/name: minio-server-svc
    app.kubernetes.io/component: service
spec:
  ports:
  - name: http
    protocol: TCP  
    port: 9000
    targetPort: 9000
  selector:
    app.kubernetes.io/name: minio
    app.kubernetes.io/component: backend
