apiVersion: v1
kind: Pod
metadata:
  name: minio-kes
  namespace: minio
  labels:
    app/name: minio-kes
    app/component: kms 
spec:
  restartPolicy: Never 
  containers:
    - name: minio-kes
      image: minio/kes:v0.17.1
      imagePullPolicy: IfNotPresent
      command: ["/bin/sh"]
      args: ["-c", "while true; do sleep 10s; done"]