apiVersion: v1
kind: Service
metadata:
  name: minio
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/component: backend
spec:
  ports:
  - port: 9000
    targetPort: 9000
  selector:
    app.kubernetes.io/name: minio
    app.kubernetes.io/component: backend
