apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    app.kubernetes.io/app: rabbitmq
    app.kubernetes.io/component: message-broker    
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/app: rabbitmq
      app.kubernetes.io/component: message-broker
  template:
    metadata:
      labels:
        app.kubernetes.io/app: rabbitmq
        app.kubernetes.io/component: message-broker
    spec:
      containers:
      - image: rabbitmq:3.6.10
        name: rabbitmq
        ports:
        - containerPort: 5672
