apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app.kubernetes.io/app: rabbitmq
    app.kubernetes.io/component: message-broker
spec:
  ports:
  - port: 5672
  selector:
    app.kubernetes.io/app: rabbitmq
    app.kubernetes.io/component: message-broker
