apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app.kubernetes.io/app: redis
    app.kubernetes.io/component: backend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/app: redis
      app.kubernetes.io/component: backend
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/app: redis
        app.kubernetes.io/component: backend
    spec:
      containers:
      - name: redis-master
        image: redis
        volumeMounts:
        - name: redis-storage
          mountPath: /data/redis        
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
      volumes:
      - name: redis-storage
        emptyDir: {} 