apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app.kubernetes.io/app: redis
    app.kubernetes.io/component: backend
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app.kubernetes.io/app: redis
    app.kubernetes.io/component: backend