apiVersion: v1
kind: Namespace
metadata:
  name: mongodb
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongodb-pvc
  namespace: mongodb
  labels:
    app/name: mongodb
    app/component: storage
spec:
  # storageClassName: use default storage class or uncomment to specify
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-admin-creds
  namespace: mongodb
  labels:
    app/name: mongodb
    app/component: creds
data:
  username: bW9uZ29kYl9hZG1pbg==
  password: Y2hhbmdlTUUxMjMh
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: mongodb
  labels:
    app/name: mongodb
    app/component: backend
spec:
  selector:
    matchLabels:
      app/name: mongodb
      app/component: backend
  replicas: 1
  template:
    metadata:
      labels:
        app/name: mongodb
        app/component: backend
    spec:
      containers:
        - name: mongodb-server
          image: mongo:4.4
          args:
            - --bind_ip
            - 0.0.0.0
          ports:
            - name: mongodb-port
              containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-admin-creds
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-admin-creds
                  key: password
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: mongodb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
  namespace: mongodb
  labels:
    app/name: mongodb
    app/component: server-service
spec:
  type: ClusterIP
  ports:
  - name: mongodb-port
    protocol: TCP  
    port: 27017
    targetPort: 27017
  selector:
    app/name: mongodb
    app/component: backend
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-lb
  namespace: mongodb
  labels:
    app/name: mongodb
    app/component: server-loadbalancer    
spec:
  type: LoadBalancer
  ports:
  - name: mongodb-port
    protocol: TCP  
    port: 27017
    targetPort: 27017
  selector:
    app/name: mongodb
    app/component: backend 
