apiVersion: v1
kind: Service
metadata:
  name: mongodb-nodeport
  labels:
    app: database
spec:
  type: NodePort
  ports:
  - port: 27017
    name: mongodb-port
    nodePort: 30017
  selector:
    selector: mongodb