apiVersion: v1
kind: Service
metadata:
  name: mssql
  labels:
    app.kubernetes.io/name: mssql
    app.kubernetes.io/component: backend
spec:
  ports:
  - port: 1433
    targetPort: 1433
  selector:
    app.kubernetes.io/name: mssql
    app.kubernetes.io/component: backend 