kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pvc8gb
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi